-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 19:08:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`perifl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`perfil` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `perfil` VARCHAR(45) NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_perifl1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `chat`.`perifl` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`mensaje` (
  `id` INT NOT NULL,
  `mensaje` VARCHAR(45) NULL,
  `emisor` VARCHAR(45) NULL,
  `receptor` VARCHAR(45) NULL,
  `fecha_hora` DATE NULL,
  `url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`contacto` (
  `id` INT NOT NULL,
  `amigo` VARCHAR(45) NULL,
  `bloquear` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contacto_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `chat`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`contacto_mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`contacto_mensaje` (
  `id_mensaje` INT NOT NULL,
  `id_contacto` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`, `id_contacto`),
  CONSTRAINT `fk_mensaje_has_contacto_mensaje`
    FOREIGN KEY (`id_mensaje`)
    REFERENCES `chat`.`mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_has_contacto_contacto1`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `chat`.`contacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
